//  Extension.swift
//  mathQuiz
//  Created by Анастасия Набатова on 23/5/24.

import Foundation
import SwiftUI

extension QuizViewModel {
    
    static var quizData: [QuizModel] {
        [
            QuizModel(theme: "Test", question: "000000",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Colors.blueButton),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Colors.blueButton),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Colors.blueButton)]),
            
            QuizModel(theme: "Fractions", question: "What is 5/6 - 1/3?",
                      answer: "B",
                      optionsList: [QuizOption(id: 41, optionId: "A", option: "1/6", color: Colors.blueButton),
                                    QuizOption(id: 42, optionId: "B", option: "1/2", color: Colors.blueButton),
                                    QuizOption(id: 43, optionId: "C", option: "1/3", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 1/2 + 1/4?",
                      answer: "A", 
                      optionsList: [QuizOption(id: 101, optionId: "A", option: "3/4", color: Colors.blueButton),
                                    QuizOption(id: 102, optionId: "B", option: "1/4", color: Colors.blueButton),
                                    QuizOption(id: 103, optionId: "C", option: "1/2", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 5/8 - 1/4?",
                      answer: "B", 
                      optionsList: [QuizOption(id: 104, optionId: "A", option: "3/4", color: Colors.blueButton),
                                    QuizOption(id: 105, optionId: "B", option: "3/8", color: Colors.blueButton),
                                    QuizOption(id: 106, optionId: "C", option: "7/8", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 2/3 * 3/4?",
                      answer: "A",
                      optionsList: [QuizOption(id: 107, optionId: "A", option: "1/2", color: Colors.blueButton),
                                    QuizOption(id: 108, optionId: "B", option: "5/12", color: Colors.blueButton),
                                    QuizOption(id: 109, optionId: "C", option: "3/4", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 4/5 ÷ 2/3?",
                      answer: "C", 
                      optionsList: [QuizOption(id: 110, optionId: "A", option: "2/3", color: Colors.blueButton),
                                    QuizOption(id: 111, optionId: "B", option: "6/5", color: Colors.blueButton),
                                    QuizOption(id: 112, optionId: "C", option: "6/5", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "Which of the following is the simplest form of 8/12?",
                      answer: "B", 
                      optionsList: [QuizOption(id: 113, optionId: "A", option: "2/3", color: Colors.blueButton),
                                    QuizOption(id: 114, optionId: "B", option: "2/3", color: Colors.blueButton),
                                    QuizOption(id: 115, optionId: "C", option: "4/6", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 3/5 * 4/7?",
                      answer: "A",
                      optionsList: [QuizOption(id: 51, optionId: "A", option: "12/35", color: Colors.blueButton),
                                    QuizOption(id: 52, optionId: "B", option: "7/20", color: Colors.blueButton),
                                    QuizOption(id: 53, optionId: "C", option: "4/15", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 3/4 + 2/3?",
                      answer: "D",
                      optionsList: [QuizOption(id: 61, optionId: "A", option: "1/2", color: Colors.blueButton),
                                    QuizOption(id: 62, optionId: "B", option: "5/7", color: Colors.blueButton),
                                    QuizOption(id: 63, optionId: "C", option: "5/6", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 2/5 - 1/4?",
                      answer: "C",
                      optionsList: [QuizOption(id: 71, optionId: "A", option: "1/20", color: Colors.blueButton),
                                    QuizOption(id: 72, optionId: "B", option: "1/10", color: Colors.blueButton),
                                    QuizOption(id: 73, optionId: "C", option: "3/20", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 3/8 * 5/6?",
                      answer: "B",
                      optionsList: [QuizOption(id: 81, optionId: "A", option: "15/48", color: Colors.blueButton),
                                    QuizOption(id: 82, optionId: "B", option: "5/16", color: Colors.blueButton),
                                    QuizOption(id: 83, optionId: "C", option: "15/24", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 4/5 + 1/2?",
                      answer: "A",
                      optionsList: [QuizOption(id: 91, optionId: "A", option: "9/10", color: Colors.blueButton),
                                    QuizOption(id: 92, optionId: "B", option: "3/4", color: Colors.blueButton),
                                    QuizOption(id: 93, optionId: "C", option: "9/10", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 5/6 - 2/3?",
                      answer: "B",
                      optionsList: [QuizOption(id: 101, optionId: "A", option: "1/6", color: Colors.blueButton),
                                    QuizOption(id: 102, optionId: "B", option: "1/6", color: Colors.blueButton),
                                    QuizOption(id: 103, optionId: "C", option: "1/2", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 3/4 * 2/3?",
                      answer: "A",
                      optionsList: [QuizOption(id: 111, optionId: "A", option: "1/2", color: Colors.blueButton),
                                    QuizOption(id: 112, optionId: "B", option: "2/3", color: Colors.blueButton),
                                    QuizOption(id: 113, optionId: "C", option: "3/4", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 7/10 + 1/5?",
                      answer: "A",
                      optionsList: [QuizOption(id: 116, optionId: "A", option: "9/10", color: Colors.blueButton),
                                    QuizOption(id: 117, optionId: "B", option: "7/15", color: Colors.blueButton),
                                    QuizOption(id: 118, optionId: "C", option: "8/10", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 3/4 - 1/8?",
                      answer: "C", 
                      optionsList: [QuizOption(id: 119, optionId: "A", option: "1/2", color: Colors.blueButton),
                                    QuizOption(id: 120, optionId: "B", option: "5/8", color: Colors.blueButton),
                                    QuizOption(id: 121, optionId: "C", option: "5/8", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 3/4 - 1/8?",
                      answer: "C",
                      optionsList: [QuizOption(id: 119, optionId: "A", option: "1/2", color: Colors.blueButton),
                                    QuizOption(id: 120, optionId: "B", option: "5/8", color: Colors.blueButton),
                                    QuizOption(id: 121, optionId: "C", option: "5/8", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 2/5 * 3/7?",
                      answer: "B",
                      optionsList: [QuizOption(id: 122, optionId: "A", option: "6/35", color: Colors.blueButton),
                                    QuizOption(id: 123, optionId: "B", option: "6/35", color: Colors.blueButton),
                                    QuizOption(id: 124, optionId: "C", option: "2/7", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is 4/9 ÷ 2/3?",
                      answer: "A", 
                      optionsList: [QuizOption(id: 125, optionId: "A", option: "2/3", color: Colors.blueButton),
                                    QuizOption(id: 126, optionId: "B", option: "6/9", color: Colors.blueButton),
                                    QuizOption(id: 127, optionId: "C", option: "1/3", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions", question: "What is the result of (5/6) + (7/12)?",
                      answer: "C",
                      optionsList: [QuizOption(id: 128, optionId: "A", option: "9/12", color: Colors.blueButton),
                                    QuizOption(id: 129, optionId: "B", option: "5/6", color: Colors.blueButton),
                                    QuizOption(id: 130, optionId: "C", option: "4/4", color: Colors.blueButton)]),
            QuizModel(theme: "Сomparing and simplifying fractions", question: "Which is greater: 2/3 or 3/4?",
                      answer: "B", 
                      optionsList: [QuizOption(id: 131, optionId: "A", option: "2/3", color: Colors.blueButton),
                                    QuizOption(id: 132, optionId: "B", option: "3/4", color: Colors.blueButton),
                                    QuizOption(id: 133, optionId: "C", option: "They are equal", color: Colors.blueButton)]),
            QuizModel(theme: "Сomparing and simplifying fractions", question: "What is the simplest form of 9/15?",
                      answer: "A",
                      optionsList: [QuizOption(id: 134, optionId: "A", option: "3/5", color: Colors.blueButton),
                                    QuizOption(id: 135, optionId: "B", option: "9/15", color: Colors.blueButton),
                                    QuizOption(id: 136, optionId: "C", option: "1/2", color: Colors.blueButton)]),
            QuizModel(theme: "Сomparing and simplifying fractions", question: "Which fraction is smaller: 5/8 or 7/8?",
                      answer: "C",
                      optionsList: [QuizOption(id: 137, optionId: "A", option: "5/8", color: Colors.blueButton),
                                    QuizOption(id: 138, optionId: "B", option: "7/8", color: Colors.blueButton),
                                    QuizOption(id: 139, optionId: "C", option: "They are equal", color: Colors.blueButton)]),
            QuizModel(theme: "Сomparing and simplifying fractions", question: "What is 4/9 compared to 2/3?",
                      answer: "B",
                      optionsList: [QuizOption(id: 140, optionId: "A", option: "4/9 is greater", color: Colors.blueButton),
                                    QuizOption(id: 141, optionId: "B", option: "2/3 is greater", color: Colors.blueButton),
                                    QuizOption(id: 142, optionId: "C", option: "They are equal", color: Colors.blueButton)]),
            QuizModel(theme: "Сomparing and simplifying fractions", question: "Simplify 16/20.",
                      answer: "A",
                      optionsList: [QuizOption(id: 143, optionId: "A", option: "4/5", color: Colors.blueButton),
                                    QuizOption(id: 144, optionId: "B", option: "8/10", color: Colors.blueButton),
                                    QuizOption(id: 145, optionId: "C", option: "2/5", color: Colors.blueButton)]),
            
            QuizModel(theme: "Numerical Methods", question: "What is the bisection method used for?",
                      answer: "C",
                      optionsList: [QuizOption(id: 501, optionId: "A", option: "Solving linear equations", color: Colors.blueButton),
                                    QuizOption(id: 502, optionId: "B", option: "Finding matrix eigenvalues", color: Colors.blueButton),
                                    QuizOption(id: 503, optionId: "C", option: "Finding roots of a function", color: Colors.blueButton)]),
              
            QuizModel(theme: "Numerical Methods", question: "What is the Newton-Raphson method used for?",
                      answer: "B",
                      optionsList: [QuizOption(id: 504, optionId: "A", option: "Solving differential equations", color: Colors.blueButton),
                                    QuizOption(id: 505, optionId: "B", option: "Finding roots of a function", color: Colors.blueButton),
                                    QuizOption(id: 506, optionId: "C", option: "Finding integrals", color: Colors.blueButton)]),
             
            QuizModel(theme: "Numerical Methods", question: "What is the trapezoidal rule used for?",
                      answer: "A",
                      optionsList: [QuizOption(id: 507, optionId: "A", option: "Approximating the definite integral of a function", color: Colors.blueButton),
                                    QuizOption(id: 508, optionId: "B", option: "Solving a linear system", color: Colors.blueButton),
                                    QuizOption(id: 509, optionId: "C", option: "Approximating derivatives", color: Colors.blueButton)]),
              
            QuizModel(theme: "Numerical Methods", question: "What is the condition number of a matrix used to assess?",
                      answer: "C",
                      optionsList: [QuizOption(id: 510, optionId: "A", option: "The size of the matrix", color: Colors.blueButton),
                                    QuizOption(id: 511, optionId: "B", option: "The rank of the matrix", color: Colors.blueButton),
                                    QuizOption(id: 512, optionId: "C", option: "The sensitivity of the solution of a linear system to changes in the input", color: Colors.blueButton)]),
              
            QuizModel(theme: "Numerical Methods", question: "What is Gaussian elimination used for?",
                      answer: "B",
                      optionsList: [QuizOption(id: 513, optionId: "A", option: "Calculating determinants", color: Colors.blueButton),
                                    QuizOption(id: 514, optionId: "B", option: "Solving systems of linear equations", color: Colors.blueButton),
                                    QuizOption(id: 515, optionId: "C", option: "Calculating eigenvalues", color: Colors.blueButton)]),
               
            QuizModel(theme: "Numerical Methods", question: "What is the purpose of the LU decomposition?",
                      answer: "A",
                      optionsList: [QuizOption(id: 516, optionId: "A", option: "To decompose a matrix into a lower and upper triangular matrix", color: Colors.blueButton),
                                    QuizOption(id: 517, optionId: "B", option: "To calculate eigenvalues", color: Colors.blueButton),
                                    QuizOption(id: 518, optionId: "C", option: "To solve differential equations", color: Colors.blueButton)]),
               
            QuizModel(theme: "Numerical Methods", question: "What is the Runge-Kutta method used for?",
                      answer: "C",
                      optionsList: [QuizOption(id: 519, optionId: "A", option: "Finding matrix inverses", color: Colors.blueButton),
                                    QuizOption(id: 520, optionId: "B", option: "Calculating determinants", color: Colors.blueButton),
                                    QuizOption(id: 521, optionId: "C", option: "Solving ordinary differential equations", color: Colors.blueButton)]),
             
            QuizModel(theme: "Numerical Methods", question: "What is the Monte Carlo method used for?",
                      answer: "B",
                      optionsList: [QuizOption(id: 522, optionId: "A", option: "Finding exact solutions to integrals", color: Colors.blueButton),
                                    QuizOption(id: 523, optionId: "B", option: "Estimating solutions through random sampling", color: Colors.blueButton),
                                    QuizOption(id: 524, optionId: "C", option: "Solving linear systems", color: Colors.blueButton)]),
               
            QuizModel(theme: "Numerical Methods", question: "What is the Jacobi method used for?",
                      answer: "A",
                      optionsList: [QuizOption(id: 525, optionId: "A", option: "Iteratively solving systems of linear equations", color: Colors.blueButton),
                                    QuizOption(id: 526, optionId: "B", option: "Calculating integrals", color: Colors.blueButton),
                                    QuizOption(id: 527, optionId: "C", option: "Finding eigenvalues", color: Colors.blueButton)]),
               
            QuizModel(theme: "Numerical Methods", question: "What is the purpose of Cholesky decomposition?",
                      answer: "C",
                      optionsList: [QuizOption(id: 528, optionId: "A", option: "Calculating matrix inverses", color: Colors.blueButton),
                                    QuizOption(id: 529, optionId: "B", option: "Finding matrix determinants", color: Colors.blueButton),
                                    QuizOption(id: 530, optionId: "C", option: "Decomposing a matrix into a product of a lower triangular matrix and its conjugate transpose", color: Colors.blueButton)]),
            
            QuizModel(theme: "Fractions and percentages", question: "Convert 3/4 to a percentage.",
                      answer: "B",
                      optionsList: [QuizOption(id: 146, optionId: "A", option: "25%", color: Colors.blueButton),
                                    QuizOption(id: 147, optionId: "B", option: "75%", color: Colors.blueButton),
                                    QuizOption(id: 148, optionId: "C", option: "50%", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions and percentages", question: "What is 20% of 150?",
                      answer: "A", 
                      optionsList: [QuizOption(id: 149, optionId: "A", option: "30", color: Colors.blueButton),
                                    QuizOption(id: 150, optionId: "B", option: "15", color: Colors.blueButton),
                                    QuizOption(id: 151, optionId: "C", option: "45", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions and percentages", question: "Convert 0.25 to a fraction.",
                      answer: "A", 
                      optionsList: [QuizOption(id: 152, optionId: "A", option: "1/4", color: Colors.blueButton),
                                    QuizOption(id: 153, optionId: "B", option: "1/2", color: Colors.blueButton),
                                    QuizOption(id: 154, optionId: "C", option: "1/5", color: Colors.blueButton)]),
            QuizModel(theme: "Fractions and percentages", question: "What is 150% as a fraction?",
                      answer: "C", 
                      optionsList: [QuizOption(id: 155, optionId: "A", option: "3/2", color: Colors.blueButton),
                                    QuizOption(id: 156, optionId: "B", option: "1/1", color: Colors.blueButton),
                                    QuizOption(id: 157, optionId: "C", option: "3/2", color: Colors.blueButton)]),
            
            QuizModel(theme: "Fractions and percentages", question: "What is 5/8 as a percentage?",
                      answer: "A",
                      optionsList: [QuizOption(id: 158, optionId: "A", option: "62.5%", color: Colors.blueButton),
                                    QuizOption(id: 159, optionId: "B", option: "75%", color: Colors.blueButton),
                                    QuizOption(id: 160, optionId: "C", option: "50%", color: Colors.blueButton)]),
            
            QuizModel(theme: "Negative Numbers", question: "What is -7 + 5?",
                      answer: "B", 
                      optionsList: [QuizOption(id: 161, optionId: "A", option: "-12", color: Colors.blueButton),
                                    QuizOption(id: 162, optionId: "B", option: "-2", color: Colors.blueButton),
                                    QuizOption(id: 163, optionId: "C", option: "12", color: Colors.blueButton)]),
            
            QuizModel(theme: "Negative Numbers", question: "What is -8 - (-3)?",
                      answer: "C", 
                      optionsList: [QuizOption(id: 164, optionId: "A", option: "-11", color: Colors.blueButton),
                                    QuizOption(id: 165, optionId: "B", option: "-5", color: Colors.blueButton),
                                    QuizOption(id: 166, optionId: "C", option: "-5", color: Colors.blueButton)]),
            QuizModel(theme: "Negative Numbers", question: "What is -4 * (-3)?",
                      answer: "A", 
                      optionsList: [QuizOption(id: 167, optionId: "A", option: "12", color: Colors.blueButton),
                                    QuizOption(id: 168, optionId: "B", option: "-12", color: Colors.blueButton),
                                    QuizOption(id: 169, optionId: "C", option: "7", color: Colors.blueButton)]),
            QuizModel(theme: "Negative Numbers", question: "What is -15 ÷ 3?",
                      answer: "B", 
                      optionsList: [QuizOption(id: 170, optionId: "A", option: "5", color: Colors.blueButton),
                                    QuizOption(id: 171, optionId: "B", option: "-5", color: Colors.blueButton),
                                    QuizOption(id: 172, optionId: "C", option: "15", color: Colors.blueButton)]),
            QuizModel(theme: "Negative Numbers", question: "Which number is greater: -7 or -4?",
                      answer: "C",
                      optionsList: [QuizOption(id: 173, optionId: "A", option: "-7", color: Colors.blueButton),
                                    QuizOption(id: 174, optionId: "B", option: "-4", color: Colors.blueButton),
                                    QuizOption(id: 175, optionId: "C", option: "-4", color: Colors.blueButton)]),
            QuizModel(theme: "Negative numbers", question: "1/4?",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Colors.blueButton),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Colors.blueButton),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Colors.blueButton)]),
            QuizModel(theme: "Negative numbers", question: "1/4?",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Colors.blueButton),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Colors.blueButton),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Colors.blueButton)]),
            QuizModel(theme: "Negative numbers", question: "1/4?",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Colors.blueButton),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Colors.blueButton),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Colors.blueButton)]),
            QuizModel(theme: "Operations with negative numbers", question: "What is -9 + (-3)?",
                      answer: "A",
                      optionsList: [QuizOption(id: 176, optionId: "A", option: "-12", color: Colors.blueButton),
                                    QuizOption(id: 177, optionId: "B", option: "-6", color: Colors.blueButton),
                                    QuizOption(id: 178, optionId: "C", option: "-9", color: Colors.blueButton)]),
            QuizModel(theme: "Operations with negative numbers", question: "What is -6 - (-2)?",
                      answer: "C", 
                      optionsList: [QuizOption(id: 179, optionId: "A", option: "-8", color: Colors.blueButton),
                                    QuizOption(id: 180, optionId: "B", option: "-4", color: Colors.blueButton),
                                    QuizOption(id: 181, optionId: "C", option: "-4", color: Colors.blueButton)]),
            QuizModel(theme: "Operations with negative numbers", question: "What is -3 * 5?",
                      answer: "B", 
                      optionsList: [QuizOption(id: 182, optionId: "A", option: "-15", color: Colors.blueButton),
                                    QuizOption(id: 183, optionId: "B", option: "-15", color: Colors.blueButton),
                                    QuizOption(id: 184, optionId: "C", option: "15", color: Colors.blueButton)]),
            QuizModel(theme: "Operations with negative numbers", question: "What is -12 ÷ (-4)?",
                      answer: "A",
                      optionsList: [QuizOption(id: 185, optionId: "A", option: "3", color: Colors.blueButton),
                                    QuizOption(id: 186, optionId: "B", option: "-3", color: Colors.blueButton),
                                    QuizOption(id: 187, optionId: "C", option: "-6", color: Colors.blueButton)]),
            QuizModel(theme: "Operations with negative numbers", question: "What is -2 - (-7)?",
                      answer: "C",
                      optionsList: [QuizOption(id: 188, optionId: "A", option: "-9", color: Colors.blueButton),
                                    QuizOption(id: 189, optionId: "B", option: "5", color: Colors.blueButton),
                                    QuizOption(id: 190, optionId: "C", option: "5", color: Colors.blueButton)]),
            
            QuizModel(theme: "Linear Algebra", question: "What is the determinant of a 2x2 matrix [[a, b], [c, d]]?", answer: "B", optionsList: [
                    QuizOption(id: 201, optionId: "A", option: "a + d", color: Colors.blueButton),
                    QuizOption(id: 202, optionId: "B", option: "ad - bc", color: Colors.blueButton),
                    QuizOption(id: 203, optionId: "C", option: "ab + cd", color: Colors.blueButton)]),
               
            QuizModel(theme: "Linear Algebra", question: "What is the trace of a matrix?", answer: "C", optionsList: [
                    QuizOption(id: 204, optionId: "A", option: "Sum of all elements", color: Colors.blueButton),
                    QuizOption(id: 205, optionId: "B", option: "Sum of diagonal elements", color: Colors.blueButton),
                    QuizOption(id: 206, optionId: "C", option: "Sum of main diagonal elements", color: Colors.blueButton)]),
              
            QuizModel(theme: "Linear Algebra", question: "What is the rank of a matrix?", answer: "A", optionsList: [
                    QuizOption(id: 207, optionId: "A", option: "Number of linearly independent rows or columns", color: Colors.blueButton),
                    QuizOption(id: 208, optionId: "B", option: "The dimension of the matrix", color: Colors.blueButton),
                    QuizOption(id: 209, optionId: "C", option: "Number of non-zero elements", color: Colors.blueButton)]),
               
            QuizModel(theme: "Linear Algebra", question: "What is the inverse of matrix A?", answer: "C", optionsList: [
                    QuizOption(id: 210, optionId: "A", option: "1/det(A) * adj(A)", color: Colors.blueButton),
                    QuizOption(id: 211, optionId: "B", option: "adj(A) / det(A)", color: Colors.blueButton),
                    QuizOption(id: 212, optionId: "C", option: "(1/det(A)) * adj(A)", color: Colors.blueButton)]),
                
            QuizModel(theme: "Linear Algebra", question: "What is a vector space?", answer: "B", optionsList: [
                    QuizOption(id: 213, optionId: "A", option: "A set of vectors", color: Colors.blueButton),
                    QuizOption(id: 214, optionId: "B", option: "A set of vectors with defined operations of vector addition and scalar multiplication", color: Colors.blueButton),
                    QuizOption(id: 215, optionId: "C", option: "A set of linearly independent vectors", color: Colors.blueButton)]),
               
            QuizModel(theme: "Linear Algebra", question: "What does it mean for vectors to be orthogonal?", answer: "A", optionsList: [
                    QuizOption(id: 216, optionId: "A", option: "Their dot product is zero", color: Colors.blueButton),
                    QuizOption(id: 217, optionId: "B", option: "Their cross product is zero", color: Colors.blueButton),
                    QuizOption(id: 218, optionId: "C", option: "They are linearly dependent", color: Colors.blueButton)]),
               
            QuizModel(theme: "Linear Algebra", question: "What is an eigenvalue?", answer: "B", optionsList: [
                    QuizOption(id: 219, optionId: "A", option: "A scalar that scales an eigenvector", color: Colors.blueButton),
                    QuizOption(id: 220, optionId: "B", option: "A scalar associated with a matrix equation Av = λv", color: Colors.blueButton),
                    QuizOption(id: 221, optionId: "C", option: "The determinant of the matrix", color: Colors.blueButton)]),
            
            QuizModel(theme: "Linear Algebra", question: "What is the dot product of two vectors?", answer: "C", optionsList: [
                    QuizOption(id: 222, optionId: "A", option: "A cross product", color: Colors.blueButton),
                    QuizOption(id: 223, optionId: "B", option: "A scalar product of two perpendicular vectors", color: Colors.blueButton),
                    QuizOption(id: 224, optionId: "C", option: "A scalar product of two vectors", color: Colors.blueButton)]),
               
            QuizModel(theme: "Linear Algebra", question: "What does it mean for a matrix to be singular?", answer: "B", optionsList: [
                    QuizOption(id: 225, optionId: "A", option: "It has no inverse", color: Colors.blueButton),
                    QuizOption(id: 226, optionId: "B", option: "Its determinant is zero", color: Colors.blueButton),
                    QuizOption(id: 227, optionId: "C", option: "Its rank is full", color: Colors.blueButton)]),
               
            QuizModel(theme: "Linear Algebra", question: "What is a basis of a vector space?", answer: "A", optionsList: [
                    QuizOption(id: 228, optionId: "A", option: "A set of linearly independent vectors that span the space", color: Colors.blueButton),
                    QuizOption(id: 229, optionId: "B", option: "A set of all vectors in the space", color: Colors.blueButton),
                    QuizOption(id: 230, optionId: "C", option: "A set of orthogonal vectors", color: Colors.blueButton)]),
        
            QuizModel(theme: "Systems of Equations", question: "Solve the system: x + y = 10 and x - y = 2",
                      answer: "A",
                      optionsList: [QuizOption(id: 191, optionId: "A", option: "x = 6, y = 4", color: Colors.blueButton),
                                    QuizOption(id: 192, optionId: "B", option: "x = 8, y = 2", color: Colors.blueButton),
                                    QuizOption(id: 193, optionId: "C", option: "x = 5, y = 5", color: Colors.blueButton)]),
            QuizModel(theme: "Systems of Equations", question: "Solve the system: 2x + 3y = 12 and x - y = 1",
                      answer: "B", 
                      optionsList: [QuizOption(id: 194, optionId: "A", option: "x = 5, y = 2", color: Colors.blueButton),
                                    QuizOption(id: 195, optionId: "B", option: "x = 3, y = 2", color: Colors.blueButton),
                                    QuizOption(id: 196, optionId: "C", option: "x = 4, y = 1", color: Colors.blueButton)]),
            QuizModel(theme: "Systems of Equations", question: "Solve the system: x + 2y = 7 and 3x - y = 5",
                      answer: "C", 
                      optionsList: [QuizOption(id: 197, optionId: "A", option: "x = 2, y = 3", color: Colors.blueButton),
                                    QuizOption(id: 198, optionId: "B", option: "x = 3, y = 2", color: Colors.blueButton),
                                    QuizOption(id: 199, optionId: "C", option: "x = 1, y = 3", color: Colors.blueButton)]),
            QuizModel(theme: "Systems of Equations", question: "Solve the system: 4x - 5y = 11 and 2x + y = 6",
                      answer: "A",
                      optionsList: [QuizOption(id: 200, optionId: "A", option: "x = 3, y = 2", color: Colors.blueButton),
                                    QuizOption(id: 201, optionId: "B", option: "x = 2, y = 3", color: Colors.blueButton),
                                    QuizOption(id: 202, optionId: "C", option: "x = 4, y = 1", color: Colors.blueButton)]),
            QuizModel(theme: "Systems of Equations", question: "Solve the system using substitution: x = 2y + 1 and 3x - 2y = 7",
                      answer: "B", 
                      optionsList: [QuizOption(id: 203, optionId: "A", option: "x = 3, y = 1", color: Colors.blueButton),
                                    QuizOption(id: 204, optionId: "B", option: "x = 4, y = 2", color: Colors.blueButton),
                                    QuizOption(id: 205, optionId: "C", option: "x = 2, y = 1", color: Colors.blueButton)]),
            
            QuizModel(theme: "Probability Theory", question: "What is the probability of flipping a fair coin and getting heads?",
                      answer: "B",
                      optionsList: [QuizOption(id: 301, optionId: "A", option: "1", color: Colors.blueButton),
                                    QuizOption(id: 302, optionId: "B", option: "0.5", color: Colors.blueButton),
                                    QuizOption(id: 303, optionId: "C", option: "0", color: Colors.blueButton)]),
            
            QuizModel(theme: "Probability Theory", question: "What is the expected value of a fair six-sided die roll?", 
                      answer: "A", optionsList: [QuizOption(id: 304, optionId: "A", option: "3.5", color: Colors.blueButton),
                                                 QuizOption(id: 305, optionId: "B", option: "3", color: Colors.blueButton),
                                                 QuizOption(id: 306, optionId: "C", option: "4", color: Colors.blueButton)]),
            
            QuizModel(theme: "Probability Theory", question: "What is the variance of a single roll of a fair six-sided die?", 
                      answer: "C",
                      optionsList: [QuizOption(id: 307, optionId: "A", option: "2.5", color: Colors.blueButton),
                                    QuizOption(id: 308, optionId: "B", option: "3", color: Colors.blueButton),
                                    QuizOption(id: 309, optionId: "C", option: "35/12", color: Colors.blueButton)]),
            
            QuizModel(theme: "Probability Theory", question: "What is the probability of drawing an ace from a standard deck of cards?",
                      answer: "B",
                      optionsList: [QuizOption(id: 310, optionId: "A", option: "1/26", color: Colors.blueButton),
                                    QuizOption(id: 311, optionId: "B", option: "1/13", color: Colors.blueButton),
                                    QuizOption(id: 312, optionId: "C", option: "1/52", color: Colors.blueButton)]),
           
            QuizModel(theme: "Probability Theory", question: "What is the probability of getting a sum of 7 when rolling two dice?",
                      answer: "A", 
                      optionsList: [QuizOption(id: 313, optionId: "A", option: "1/6", color: Colors.blueButton),
                                    QuizOption(id: 314, optionId: "B", option: "1/12", color: Colors.blueButton),
                                    QuizOption(id: 315, optionId: "C", option: "1/36", color: Colors.blueButton)]),
            
            QuizModel(theme: "Probability Theory", question: "What is the probability of getting two heads when flipping two coins?",
                      answer: "B",
                      optionsList: [QuizOption(id: 316, optionId: "A", option: "1/3", color: Colors.blueButton),
                                    QuizOption(id: 317, optionId: "B", option: "1/4", color: Colors.blueButton),
                                    QuizOption(id: 318, optionId: "C", option: "1/2", color: Colors.blueButton)]),
            
            QuizModel(theme: "Probability Theory", question: "What is the expected value of a geometric distribution with probability p?",
                      answer: "A",
                      optionsList: [QuizOption(id: 319, optionId: "A", option: "1/p", color: Colors.blueButton),
                                    QuizOption(id: 320, optionId: "B", option: "p", color: Colors.blueButton),
                                    QuizOption(id: 321, optionId: "C", option: "1/(1-p)", color: Colors.blueButton)]),
           
            QuizModel(theme: "Probability Theory", question: "What is the probability of getting at least one head in two flips of a fair coin?",
                      answer: "B", optionsList: [QuizOption(id: 322, optionId: "A", option: "1/2", color: Colors.blueButton),
                                                 QuizOption(id: 323, optionId: "B", option: "3/4", color: Colors.blueButton),
                                                 QuizOption(id: 324, optionId: "C", option: "1", color: Colors.blueButton)]),
          
            QuizModel(theme: "Probability Theory", question: "What is the probability of drawing two aces consecutively from a deck without replacement?",
                      answer: "A",
                      optionsList: [QuizOption(id: 325, optionId: "A", option: "1/221", color: Colors.blueButton),
                                    QuizOption(id: 326, optionId: "B", option: "1/52", color: Colors.blueButton),
                                    QuizOption(id: 327, optionId: "C", option: "1/26", color: Colors.blueButton)]),
                
            QuizModel(theme: "Probability Theory", question: "What is the variance of a binomial distribution with parameters n and p?", 
                      answer: "C",
                      optionsList: [QuizOption(id: 328, optionId: "A", option: "np", color: Colors.blueButton),
                                    QuizOption(id: 329, optionId: "B", option: "p(1-p)", color: Colors.blueButton),
                                    QuizOption(id: 330, optionId: "C", option: "np(1-p)", color: Colors.blueButton)]),

            QuizModel(theme: "Nonlinear Systems", question: "Solve the system: x^2 + y^2 = 25 and x + y = 7",
                      answer: "A", 
                      optionsList: [QuizOption(id: 206, optionId: "A", option: "x = 4, y = 3", color: Colors.blueButton),
                                    QuizOption(id: 207, optionId: "B", option: "x = 5, y = 2", color: Colors.blueButton),
                                    QuizOption(id: 208, optionId: "C", option: "x = 3, y = 4", color: Colors.blueButton)]),
            QuizModel(theme: "Nonlinear Systems", question: "Solve the system: x^2 - y^2 = 4 and x + y = 6",
                      answer: "C",
                      optionsList: [QuizOption(id: 209, optionId: "A", option: "x = 5, y = 1", color: Colors.blueButton),
                                    QuizOption(id: 210, optionId: "B", option: "x = 4, y = 2", color: Colors.blueButton),
                                    QuizOption(id: 211, optionId: "C", option: "x = 5, y = 1", color: Colors.blueButton)]),
            QuizModel(theme: "Nonlinear Systems", question: "Solve the system: x^2 + y^2 = 10 and x - y = 2",
                      answer: "B", 
                      optionsList: [QuizOption(id: 212, optionId: "A", option: "x = 3, y = 1", color: Colors.blueButton),
                                    QuizOption(id: 213, optionId: "B", option: "x = 4, y = 1", color: Colors.blueButton),
                                    QuizOption(id: 214, optionId: "C", option: "x = 2, y = 3", color: Colors.blueButton)]),
            QuizModel(theme: "Nonlinear Systems", question: "Solve the system: y = x^2 and x + y = 6",
                      answer: "C",
                      optionsList: [QuizOption(id: 215, optionId: "A", option: "x = 1, y = 5", color: Colors.blueButton),
                                    QuizOption(id: 216, optionId: "B", option: "x = 2, y = 4", color: Colors.blueButton),
                                    QuizOption(id: 217, optionId: "C", option: "x = 2, y = 4", color: Colors.blueButton)]),
            QuizModel(theme: "Nonlinear Systems", question: "Solve the system: x^2 + 2y^2 = 10 and x - y = 2",
                      answer: "A", 
                      optionsList: [QuizOption(id: 218, optionId: "A", option: "x = 4, y = 1", color: Colors.blueButton),
                                    QuizOption(id: 219, optionId: "B", option: "x = 3, y = 2", color: Colors.blueButton),
                                    QuizOption(id: 220, optionId: "C", option: "x = 5, y = 1", color: Colors.blueButton)]),
            QuizModel(theme: "Applications of Systems of Equations", question: "If a shirt costs $20 and a pair of pants costs $30, and you buy 2 shirts and 3 pairs of pants, what is the total cost?",
                      answer: "A", 
                      optionsList: [QuizOption(id: 221, optionId: "A", option: "$140", color: Colors.blueButton),
                                    QuizOption(id: 222, optionId: "B", option: "$150", color: Colors.blueButton),
                                    QuizOption(id: 223, optionId: "C", option: "$120", color: Colors.blueButton)]),
            
            QuizModel(theme: "Applications of Systems of Equations", question: "A store sells pencils at $0.50 each and erasers at $1.20 each. If you buy 10 pencils and 5 erasers, what is the total cost?",
                      answer: "B", 
                      optionsList: [QuizOption(id: 224, optionId: "A", option: "$8.00", color: Colors.blueButton),
                                    QuizOption(id: 225, optionId: "B", option: "$9.00", color: Colors.blueButton),
                                    QuizOption(id: 226, optionId: "C", option: "$7.00", color: Colors.blueButton)]),
            
            QuizModel(theme: "Applications of Systems of Equations", question: "A farmer has chickens and cows. If there are 28 heads and 80 legs in total, how many chickens and cows are there?",
                      answer: "C",
                      optionsList: [QuizOption(id: 227, optionId: "A", option: "12 chickens and 16 cows", color: Colors.blueButton),
                                    QuizOption(id: 228, optionId: "B", option: "10 chickens and 18 cows", color: Colors.blueButton),
                                    QuizOption(id: 229, optionId: "C", option: "16 chickens and 12 cows", color: Colors.blueButton)]),
            
            QuizModel(theme: "Applications of Systems of Equations", question: "You have two types of tickets: adult tickets for $15 and child tickets for $10. If you sold 30 tickets and earned $400, how many of each type did you sell?",
                      answer: "B", 
                      optionsList: [QuizOption(id: 230, optionId: "A", option: "20 adult and 10 child tickets", color: Colors.blueButton),
                                    QuizOption(id: 231, optionId: "B", option: "10 adult and 20 child tickets", color: Colors.blueButton),
                                    QuizOption(id: 232, optionId: "C", option: "15 adult and 15 child tickets", color: Colors.blueButton)]),
            
            QuizModel(theme: "Applications of Systems of Equations", question: "A boat travels upstream and downstream. If it takes 4 hours to travel upstream and 3 hours downstream, and the speed of the river current is 2 mph, what is the speed of the boat in still water?",
                      answer: "A", 
                      optionsList: [QuizOption(id: 233, optionId: "A", option: "10 mph", color: Colors.blueButton),
                                    QuizOption(id: 234, optionId: "B", option: "12 mph", color: Colors.blueButton),
                                    QuizOption(id: 235, optionId: "C", option: "8 mph", color: Colors.blueButton)]),
            
            QuizModel(theme: "Matrix Analysis", question: "What is the Frobenius norm of a matrix A?", 
                      answer: "C",
                      optionsList: [QuizOption(id: 401, optionId: "A", option: "Sum of all elements of A", color: Colors.blueButton),
                                    QuizOption(id: 402, optionId: "B", option: "Sum of squares of all elements of A", color: Colors.blueButton),
                                    QuizOption(id: 403, optionId: "C", option: "Square root of the sum of squares of all elements of A", color: Colors.blueButton)]),
               
            QuizModel(theme: "Matrix Analysis", question: "What is the spectral norm of a matrix?",
                      answer: "B",
                      optionsList: [ QuizOption(id: 404, optionId: "A", option: "The largest eigenvalue", color: Colors.blueButton),
                                     QuizOption(id: 405, optionId: "B", option: "The largest singular value", color: Colors.blueButton),
                                     QuizOption(id: 406, optionId: "C", option: "The determinant of the matrix", color: Colors.blueButton)]),
              
            QuizModel(theme: "Matrix Analysis", question: "What is the trace norm of a matrix?",
                      answer: "A",
                      optionsList: [QuizOption(id: 407, optionId: "A", option: "Sum of singular values", color: Colors.blueButton),
                                    QuizOption(id: 408, optionId: "B", option: "Sum of eigenvalues", color: Colors.blueButton),
                                    QuizOption(id: 409, optionId: "C", option: "Sum of diagonal elements", color: Colors.blueButton)]),
              
            QuizModel(theme: "Matrix Analysis", question: "What is the condition number of a matrix?",
                      answer: "B",
                      optionsList: [QuizOption(id: 410, optionId: "A", option: "The ratio of largest to smallest eigenvalues", color: Colors.blueButton),
                                    QuizOption(id: 411, optionId: "B", option: "The ratio of largest to smallest singular values", color: Colors.blueButton),
                                    QuizOption(id: 412, optionId: "C", option: "The determinant of the matrix", color: Colors.blueButton)]),
              
            QuizModel(theme: "Matrix Analysis", question: "What is the Moore-Penrose pseudoinverse?",
                      answer: "C",
                      optionsList: [ QuizOption(id: 413, optionId: "A", option: "The inverse of a matrix", color: Colors.blueButton),
                                     QuizOption(id: 414, optionId: "B", option: "A matrix that approximates the inverse", color: Colors.blueButton),
                                     QuizOption(id: 415, optionId: "C", option: "The generalized inverse of a matrix for non-square matrices", color: Colors.blueButton)]),
              
            QuizModel(theme: "Matrix Analysis", question: "What is the determinant of a diagonal matrix?", answer: "A", optionsList: [
                   QuizOption(id: 416, optionId: "A", option: "Product of diagonal elements", color: Colors.blueButton),
                   QuizOption(id: 417, optionId: "B", option: "Sum of diagonal elements", color: Colors.blueButton),
                   QuizOption(id: 418, optionId: "C", option: "Sum of squares of diagonal elements", color: Colors.blueButton)
               ]),
               
            QuizModel(theme: "Matrix Analysis", question: "What is the rank of a zero matrix?",
                      answer: "B",
                      optionsList: [QuizOption(id: 419, optionId: "A", option: "Full rank", color: Colors.blueButton),
                                    QuizOption(id: 420, optionId: "B", option: "Zero", color: Colors.blueButton),
                                    QuizOption(id: 421, optionId: "C", option: "One", color: Colors.blueButton)]),
              
            QuizModel(theme: "Matrix Analysis", question: "What is a positive definite matrix?",
                      answer: "A",
                      optionsList: [QuizOption(id: 422, optionId: "A", option: "A matrix where all eigenvalues are positive", color: Colors.blueButton),
                                    QuizOption(id: 423, optionId: "B", option: "A matrix where the determinant is positive", color: Colors.blueButton),
                                    QuizOption(id: 424, optionId: "C", option: "A matrix where the trace is positive", color: Colors.blueButton)]),
            
            QuizModel(theme: "Matrix Analysis", question: "What is a unitary matrix?",
                      answer: "C", 
                      optionsList: [QuizOption(id: 425, optionId: "A", option: "A matrix with all singular values equal to one", color: Colors.blueButton),
                                    QuizOption(id: 426, optionId: "B", option: "A matrix with all eigenvalues equal to one", color: Colors.blueButton),
                                    QuizOption(id: 427, optionId: "C", option: "A matrix whose inverse is its conjugate transpose", color: Colors.blueButton)]),
               
            QuizModel(theme: "Matrix Analysis", question: "What is a singular value decomposition?",
                      answer: "A",
                      optionsList: [QuizOption(id: 428, optionId: "A", option: "A factorization of a matrix into U, Σ, V^T", color: Colors.blueButton),
                                    QuizOption(id: 429, optionId: "B", option: "A factorization of a matrix into U, V, Σ^T", color: Colors.blueButton),
                                    QuizOption(id: 430, optionId: "C", option: "A decomposition into eigenvectors", color: Colors.blueButton)]),
           
            QuizModel(theme: "Decimal Fractions", question: "What is 0.75 as a fraction?",
                      answer: "B",
                      optionsList: [QuizOption(id: 236, optionId: "A", option: "1/2", color: Colors.blueButton),
                                    QuizOption(id: 237, optionId: "B", option: "3/4", color: Colors.blueButton),
                                    QuizOption(id: 238, optionId: "C", option: "7/10", color: Colors.blueButton)]),
            
            QuizModel(theme: "Decimal Fractions", question: "What is 0.4 + 0.35?",
                      answer: "C", 
                      optionsList: [QuizOption(id: 239, optionId: "A", option: "0.75", color: Colors.blueButton),
                                    QuizOption(id: 240, optionId: "B", option: "0.85", color: Colors.blueButton),
                                    QuizOption(id: 241, optionId: "C", option: "0.75", color: Colors.blueButton)]),
            
            QuizModel(theme: "Decimal Fractions", question: "What is 1.2 ÷ 0.4?",
                      answer: "A",
                      optionsList: [QuizOption(id: 242, optionId: "A", option: "3", color: Colors.blueButton),
                                    QuizOption(id: 243, optionId: "B", option: "4", color: Colors.blueButton),
                                    QuizOption(id: 244, optionId: "C", option: "2", color: Colors.blueButton)]),
            
            QuizModel(theme: "Decimal Fractions", question: "What is 0.9 - 0.6?",
                      answer: "B",
                      optionsList: [QuizOption(id: 245, optionId: "A", option: "0.5", color: Colors.blueButton),
                                    QuizOption(id: 246, optionId: "B", option: "0.3", color: Colors.blueButton),
                                    QuizOption(id: 247, optionId: "C", option: "0.4", color: Colors.blueButton)]),
            
            QuizModel(theme: "Decimal Fractions", question: "Convert 0.625 to a fraction.",
                      answer: "C", 
                      optionsList: [QuizOption(id: 248, optionId: "A", option: "5/8", color: Colors.blueButton),
                                    QuizOption(id: 249, optionId: "B", option: "1/2", color: Colors.blueButton),
                                    QuizOption(id: 250, optionId: "C", option: "5/8", color: Colors.blueButton)]),
            
            QuizModel(theme: "Calculus", question: "What is the derivative of x^2?", answer: "B", optionsList: [
                   QuizOption(id: 101, optionId: "A", option: "x", color: Colors.blueButton),
                   QuizOption(id: 102, optionId: "B", option: "2x", color: Colors.blueButton),
                   QuizOption(id: 103, optionId: "C", option: "x^2", color: Colors.blueButton)]),
               
            QuizModel(theme: "Calculus", question: "What is the integral of 2x dx?", answer: "C", optionsList: [
                   QuizOption(id: 104, optionId: "A", option: "x^2 + C", color: Colors.blueButton),
                   QuizOption(id: 105, optionId: "B", option: "2x^2 + C", color: Colors.blueButton),
                   QuizOption(id: 106, optionId: "C", option: "x^2 + C", color: Colors.blueButton)]),
            
            QuizModel(theme: "Calculus", question: "What is the derivative of sin(x)?", answer: "A", optionsList: [
                   QuizOption(id: 107, optionId: "A", option: "cos(x)", color: Colors.blueButton),
                   QuizOption(id: 108, optionId: "B", option: "-sin(x)", color: Colors.blueButton),
                   QuizOption(id: 109, optionId: "C", option: "-cos(x)", color: Colors.blueButton)]),
              
            QuizModel(theme: "Calculus", question: "What is the derivative of e^x?", answer: "B", optionsList: [
                   QuizOption(id: 110, optionId: "A", option: "x * e^(x-1)", color: Colors.blueButton),
                   QuizOption(id: 111, optionId: "B", option: "e^x", color: Colors.blueButton),
                   QuizOption(id: 112, optionId: "C", option: "e", color: Colors.blueButton)]),
            
            QuizModel(theme: "Calculus", question: "What is the second derivative of x^3?", answer: "C", optionsList: [
                   QuizOption(id: 113, optionId: "A", option: "3x^2", color: Colors.blueButton),
                   QuizOption(id: 114, optionId: "B", option: "6x", color: Colors.blueButton),
                   QuizOption(id: 115, optionId: "C", option: "6", color: Colors.blueButton)]),
            
            QuizModel(theme: "Calculus", question: "What is the limit of (1 + 1/n)^n as n approaches infinity?", answer: "A", optionsList: [
                   QuizOption(id: 116, optionId: "A", option: "e", color: Colors.blueButton),
                   QuizOption(id: 117, optionId: "B", option: "1", color: Colors.blueButton),
                   QuizOption(id: 118, optionId: "C", option: "0", color: Colors.blueButton)]),
            
            QuizModel(theme: "Calculus", question: "What is the derivative of ln(x)?", answer: "B", optionsList: [
                   QuizOption(id: 119, optionId: "A", option: "x", color: Colors.blueButton),
                   QuizOption(id: 120, optionId: "B", option: "1/x", color: Colors.blueButton),
                   QuizOption(id: 121, optionId: "C", option: "ln(x)", color: Colors.blueButton)]),
              
            QuizModel(theme: "Calculus", question: "What is the derivative of cos(x)?", answer: "A", optionsList: [
                   QuizOption(id: 122, optionId: "A", option: "-sin(x)", color: Colors.blueButton),
                   QuizOption(id: 123, optionId: "B", option: "cos(x)", color: Colors.blueButton),
                   QuizOption(id: 124, optionId: "C", option: "sec^2(x)", color: Colors.blueButton)]),
               
            QuizModel(theme: "Calculus", question: "What is the integral of 1/x dx?", answer: "B", optionsList: [
                   QuizOption(id: 125, optionId: "A", option: "1/x + C", color: Colors.blueButton),
                   QuizOption(id: 126, optionId: "B", option: "ln|x| + C", color: Colors.blueButton),
                   QuizOption(id: 127, optionId: "C", option: "e^x + C", color: Colors.blueButton)
               ]),
    
            QuizModel(theme: "Calculus", question: "What is the derivative of tan(x)?", answer: "C", optionsList: [
                   QuizOption(id: 128, optionId: "A", option: "sin(x)", color: Colors.blueButton),
                   QuizOption(id: 129, optionId: "B", option: "cos(x)", color: Colors.blueButton),
                   QuizOption(id: 130, optionId: "C", option: "sec^2(x)", color: Colors.blueButton)]),
           
            
        ]
    }
    
    static var uniqueThemes: [String] {
        let themes = quizData.map { $0.theme }
        return Array(Set(themes))
    }
}
