//  Extension.swift
//  mathQuiz
//  Created by Анастасия Набатова on 23/5/24.

import Foundation
import SwiftUI

extension QuizViewModel {

    static var quizData: [QuizModel] {
        [
            QuizModel(theme: "Test", question: "000000",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            QuizModel(theme: "Fractions", question: "What is 5/6 - 1/3?",
                      answer: "B",
                      optionsList: [QuizOption(id: 41, optionId: "A", option: "1/6", color: Color.yellow),
                                    QuizOption(id: 42, optionId: "B", option: "1/2", color: Color.red),
                                    QuizOption(id: 43, optionId: "C", option: "1/3", color: Color.green)]),
            QuizModel(theme: "Fractions", question: "What is 3/5 * 4/7?",
                      answer: "A",
                      optionsList: [QuizOption(id: 51, optionId: "A", option: "12/35", color: Color.yellow),
                                    QuizOption(id: 52, optionId: "B", option: "7/20", color: Color.red),
                                    QuizOption(id: 53, optionId: "C", option: "4/15", color: Color.green)]),
            QuizModel(theme: "Fractions", question: "What is 3/4 + 2/3?",
                      answer: "D",
                      optionsList: [QuizOption(id: 61, optionId: "A", option: "1/2", color: Color.yellow),
                                    QuizOption(id: 62, optionId: "B", option: "5/7", color: Color.red),
                                    QuizOption(id: 63, optionId: "C", option: "5/6", color: Color.green)]),
            QuizModel(theme: "Fractions", question: "What is 2/5 - 1/4?",
                      answer: "C",
                      optionsList: [QuizOption(id: 71, optionId: "A", option: "1/20", color: Color.yellow),
                                    QuizOption(id: 72, optionId: "B", option: "1/10", color: Color.red),
                                    QuizOption(id: 73, optionId: "C", option: "3/20", color: Color.green)]),
            QuizModel(theme: "Fractions", question: "What is 3/8 * 5/6?",
                      answer: "B",
                      optionsList: [QuizOption(id: 81, optionId: "A", option: "15/48", color: Color.yellow),
                                    QuizOption(id: 82, optionId: "B", option: "5/16", color: Color.red),
                                    QuizOption(id: 83, optionId: "C", option: "15/24", color: Color.green)]),
            QuizModel(theme: "Fractions", question: "What is 4/5 + 1/2?",
                      answer: "C",
                      optionsList: [QuizOption(id: 91, optionId: "A", option: "9/10", color: Color.yellow),
                                    QuizOption(id: 92, optionId: "B", option: "3/4", color: Color.red),
                                    QuizOption(id: 93, optionId: "C", option: "9/10", color: Color.green)]),
            QuizModel(theme: "Fractions", question: "What is 5/6 - 2/3?",
                      answer: "B",
                      optionsList: [QuizOption(id: 101, optionId: "A", option: "1/6", color: Color.yellow),
                                    QuizOption(id: 102, optionId: "B", option: "1/6", color: Color.red),
                                    QuizOption(id: 103, optionId: "C", option: "1/2", color: Color.green)]),
            QuizModel(theme: "Fractions", question: "What is 3/4 * 2/3?",
                      answer: "A",
                      optionsList: [QuizOption(id: 111, optionId: "A", option: "1/2", color: Color.yellow),
                                    QuizOption(id: 112, optionId: "B", option: "2/3", color: Color.red),
                                    QuizOption(id: 113, optionId: "C", option: "3/4", color: Color.green)]),
            QuizModel(theme: "Negative numbers", question: "1/4?",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            QuizModel(theme: "Negative numbers", question: "1/4?",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            QuizModel(theme: "Negative numbers", question: "1/4?",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            
            QuizModel(theme: "System", question: "33333?",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            QuizModel(theme: "System", question: "33333",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            QuizModel(theme: "System", question: "33333",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            
            QuizModel(theme: "Multiplication table", question: "444444",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            QuizModel(theme: "Multiplication table", question: "4444444",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            QuizModel(theme: "Multiplication table", question: "4444444",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            
            QuizModel(theme: "Else", question: "5555555",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            QuizModel(theme: "Else", question: "555555",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
            QuizModel(theme: "Else", question: "55555",
                      answer: "C",
                      optionsList: [QuizOption(id: 31, optionId: "A", option: "5/12", color: Color.yellow),
                                    QuizOption(id: 32, optionId: "B", option: "3/7", color: Color.red),
                                    QuizOption(id: 33, optionId: "C", option: "11/12", color: Color.green)]),
        ]
    }
    
    static var uniqueThemes: [String] {
        let themes = quizData.map { $0.theme }
        return Array(Set(themes))
    }
}
